### ISSUE TITLE
stream coredump

### ISSUE THREAD

**Issue by cherishman2005** [cherishman2005/rtc#28]
```
(gdb) bt
#0  0x00000000007a0d2a in compat_encode ()
#1  0x00000000007a1096 in avcodec_encode_video2 ()
#2  0x00000000004a7d10 in CImageEncoder::encode (this=0x7fc430003440, pFrame=pFrame@entry=0x7fc4307e6f80, outBuf=outBuf@entry=0x7fc46d74b820 "", inOutSize=inOutSize@entry=0x7fc46d74b7ec, quality=quality@entry=2) at ImageEncoder.cpp:63
#3  0x000000000049327a in Stream::StreamThread::encodeJpeg (this=this@entry=0x35d3790, frame=frame@entry=0x7fc4307e6f80, uid="2705764546", jpeg=..., timestamp=timestamp@entry=1634253728074) at stream_thread.cpp:470
#4  0x000000000049724b in Stream::StreamThread::pushStream (this=this@entry=0x35d3790) at stream_thread.cpp:338
#5  0x0000000000498f94 in Stream::StreamThread::startPushStream (this=this@entry=0x35d3790) at stream_thread.cpp:211
#6  0x00000000004991e5 in Stream::StreamThread::worker (param=0x35d3790) at stream_thread.cpp:128
#7  0x00007fc4c460b6ba in start_thread (arg=0x7fc46d7c9700) at pthread_create.c:333
#8  0x00007fc4c3aa041d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by cherishman2005** [comment]
```
(gdb) f 2
#2  0x00000000004a7d10 in CImageEncoder::encode (this=0x7fc430003440, pFrame=pFrame@entry=0x7fc4307e6f80, outBuf=outBuf@entry=0x7fc46d74b820 "", inOutSize=inOutSize@entry=0x7fc46d74b7ec, quality=quality@entry=2) at ImageEncoder.cpp:63
63      ImageEncoder.cpp: No such file or directory.
(gdb) p *pFrame
$1 = {data = {0x7fc3fc15ec40 '\200' <repeats 16 times>, 0x7fc3fd752dc0 "\200\200\200\200\200\200\200\200", 0x7fc430a50d00 "\200\200\200\200\200\200\200\200", 0x0, 0x0, 0x0, 0x0, 0x0}, linesize = {128, 64, 64, 0, 0, 0, 0, 0}, 
  extended_data = 0x7fc4307e6f80, width = 16, height = 179840, nb_samples = 0, format = 0, key_frame = 1, pict_type = AV_PICTURE_TYPE_I, sample_aspect_ratio = {num = 0, den = 1}, pts = 5053267, pkt_pts = 5053267, pkt_dts = 5061900, 
  coded_picture_number = 10522, display_picture_number = 0, quality = 0, opaque = 0x0, error = {0, 0, 0, 0, 0, 0, 0, 0}, repeat_pict = 0, interlaced_frame = 0, top_field_first = 1, palette_has_changed = 0, 
  reordered_opaque = -9223372036854775808, sample_rate = 0, channel_layout = 0, buf = {0x7fc3fe2da040, 0x7fc43001f440, 0x7fc430a50c00, 0x0, 0x0, 0x0, 0x0, 0x0}, extended_buf = 0x0, nb_extended_buf = 0, side_data = 0x0, 
  nb_side_data = 0, flags = 0, color_range = AVCOL_RANGE_MPEG, color_primaries = AVCOL_PRI_UNSPECIFIED, color_trc = AVCOL_TRC_UNSPECIFIED, colorspace = AVCOL_SPC_UNSPECIFIED, chroma_location = AVCHROMA_LOC_UNSPECIFIED, 
  best_effort_timestamp = 5061900, pkt_pos = -1, pkt_duration = 0, metadata = 0x7fc431a92b00, decode_error_flags = 12, channels = 0, pkt_size = 19098, qscale_table = 0x0, qstride = 0, qscale_type = 0, qp_table_buf = 0x0, 
  hw_frames_ctx = 0x0, opaque_ref = 0x0, crop_top = 0, crop_bottom = 0, crop_left = 0, crop_right = 0, private_ref = 0x0}
```

width = 16, height = 179840 超过 500k。
