### ISSUE TITLE
Error: VideoCapture::New - failed to open capture

### ISSUE THREAD

**Issue by cherishman2005** [cherishman2005/rtc#48]
Unable to stop the stream: Inappropriate ioctl for device
/home/nodejs/face_detection/examples/utils.js:12
  const cap = new cv.VideoCapture(videoFile);
              ^

Error: VideoCapture::New - failed to open capture
    at grabFrames (/home/nodejs/face_detection/examples/utils.js:12:15)
    at Object.<anonymous> (/home/nodejs/face_detection/examples/simpleTracking0.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by cherishman2005** [comment]
11

I have solved this issue on Ubuntu 16.04.3.
```
sudo apt-get install ffmpeg
sudo apt-get install libavcodec-dev libavformat-dev libavdevice-dev
```
Rebuild OpenCV 3.3.0 with the following commands:
```
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local  -D WITH_FFMPEG=ON -D WITH_TBB=ON -D WITH_GTK=ON -D WITH_V4L=ON -D WITH_OPENGL=ON -D WITH_CUBLAS=ON -DWITH_QT=OFF -DCUDA_NVCC_FLAGS="-D_FORCE_INLINES" ..
make -j7
sudo make install
```

https://stackoverflow.com/questions/41200201/opencv-unable-to-stop-the-stream-inappropriate-ioctl-for-device
